@extends('layouts.app')

@section('title', 'Ticket Layout Editor')

@section('content')
<div class="container-fluid mt-4">
    <div class="row">
        <!-- Left: Preview -->
        <div class="col-md-7">
            <div class="card">
                <div class="card-header bg-primary text-white">
                    <h5 class="mb-0"><i class="fas fa-eye"></i> Preview</h5>
                </div>
                <div class="card-body" style="background: #f5f5f5; text-align: center;">
                    <div id="preview" style="display: inline-block; background: white; border: 2px solid #333; position: relative; margin: 20px auto;">
                        <!-- Will be generated by JS -->
                    </div>
                </div>
            </div>
        </div>

        <!-- Right: Controls -->
        <div class="col-md-5">
            <form id="configForm">
                @csrf
                
                <!-- Basic Settings -->
                <div class="card mb-3">
                    <div class="card-header bg-secondary text-white">
                        <h6 class="mb-0"><i class="fas fa-cog"></i> Cilësimet Bazike</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-group mb-2">
                            <label class="small font-weight-bold">Emri i Kompanisë</label>
                            <input type="text" class="form-control form-control-sm" name="company_name" value="{{ $config['company_name'] ?? 'ColiDecor' }}">
                        </div>

                        <div class="row">
                            <div class="col-6">
                                <label class="small font-weight-bold">Gjerësia (mm)</label>
                                <input type="number" class="form-control form-control-sm" name="ticket_width_mm" value="{{ $config['ticket_width_mm'] ?? 100 }}" min="70" max="200" step="5">
                            </div>
                            <div class="col-6">
                                <label class="small font-weight-bold">Lartësia (mm)</label>
                                <input type="number" class="form-control form-control-sm" name="ticket_height_mm" value="{{ $config['ticket_height_mm'] ?? 75 }}" min="60" max="200" step="5">
                            </div>
                        </div>

                        <div class="form-group mt-2">
                            <label class="small font-weight-bold">Orientimi</label>
                            <select class="form-control form-control-sm" name="orientation">
                                <option value="landscape" {{ ($config['orientation'] ?? 'landscape') == 'landscape' ? 'selected' : '' }}>Horizontal</option>
                                <option value="portrait" {{ ($config['orientation'] ?? 'landscape') == 'portrait' ? 'selected' : '' }}>Vertikal</option>
                            </select>
                        </div>
                    </div>
                </div>

                <!-- Logo Settings -->
                <div class="card mb-3">
                    <div class="card-header bg-secondary text-white">
                        <h6 class="mb-0"><i class="fas fa-image"></i> Logo</h6>
                    </div>
                    <div class="card-body">
                        <div class="form-check mb-2">
                            <input class="form-check-input" type="checkbox" name="show_logo" id="show_logo" {{ ($config['show_logo'] ?? true) ? 'checked' : '' }}>
                            <label class="form-check-label small" for="show_logo">Shfaq Logo</label>
                        </div>

                        <div id="logoControls">
                            <div class="form-group mb-2">
                                <label class="small font-weight-bold">Lartësia (mm)</label>
                                <input type="number" class="form-control form-control-sm" name="logo_height_mm" value="{{ $config['logo_height_mm'] ?? 6 }}" min="3" max="30" step="0.5">
                            </div>

                            <div class="form-group mb-2">
                                <label class="small font-weight-bold">Rotacioni</label>
                                <select class="form-control form-control-sm" name="logo_rotation">
                                    <option value="0" {{ ($config['logo_rotation'] ?? 0) == 0 ? 'selected' : '' }}>Horizontal (0°)</option>
                                    <option value="90" {{ ($config['logo_rotation'] ?? 0) == 90 ? 'selected' : '' }}>Vertikal (90°)</option>
                                    <option value="270" {{ ($config['logo_rotation'] ?? 0) == 270 ? 'selected' : '' }}>Vertikal (270°)</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Print Offset -->
                <div class="card mb-3">
                    <div class="card-header bg-secondary text-white">
                        <h6 class="mb-0"><i class="fas fa-arrows-alt"></i> Pozicioni për Printim</h6>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-6">
                                <label class="small font-weight-bold">Offset X (mm)</label>
                                <input type="number" class="form-control form-control-sm" name="print_offset_x" value="{{ $config['print_offset_x'] ?? 0 }}" min="-50" max="50" step="0.5">
                                <small class="text-muted">← Majtas / Djathtas →</small>
                            </div>
                            <div class="col-6">
                                <label class="small font-weight-bold">Offset Y (mm)</label>
                                <input type="number" class="form-control form-control-sm" name="print_offset_y" value="{{ $config['print_offset_y'] ?? 0 }}" min="-50" max="50" step="0.5">
                                <small class="text-muted">↑ Lart / Poshtë ↓</small>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Text Fields -->
                <div class="card mb-3">
                    <div class="card-header bg-secondary text-white">
                        <h6 class="mb-0"><i class="fas fa-text-height"></i> Fushat e Tekstit</h6>
                    </div>
                    <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                        @php
                            $textFields = [
                                'project' => 'Projekti',
                                'part_name' => 'Emri i Pjesës',
                                'dimensions' => 'Dimensionet',
                                'material' => 'Materiali',
                                'edge_banding' => 'Kantimi',
                                'date' => 'Data',
                            ];
                        @endphp

                        @foreach($textFields as $key => $label)
                        <div class="border-bottom pb-2 mb-2">
                            <div class="form-check mb-1">
                                <input class="form-check-input" type="checkbox" name="fields_visible[{{ $key }}]" id="field_{{ $key }}" {{ ($config['fields_visible'][$key] ?? true) ? 'checked' : '' }}>
                                <label class="form-check-label small font-weight-bold" for="field_{{ $key }}">{{ $label }}</label>
                            </div>

                            <div class="row">
                                <div class="col-6">
                                    <label class="small">Font Size</label>
                                    <input type="number" class="form-control form-control-sm" name="elements[{{ $key }}][font_size]" value="{{ $config['elements'][$key]['font_size'] ?? 9 }}" min="6" max="20" step="1">
                                </div>
                                <div class="col-6">
                                    <label class="small">Rotacioni</label>
                                    <select class="form-control form-control-sm" name="elements[{{ $key }}][rotation]">
                                        <option value="0" {{ ($config['elements'][$key]['rotation'] ?? 0) == 0 ? 'selected' : '' }}>0°</option>
                                        <option value="90" {{ ($config['elements'][$key]['rotation'] ?? 0) == 90 ? 'selected' : '' }}>90°</option>
                                        <option value="270" {{ ($config['elements'][$key]['rotation'] ?? 0) == 270 ? 'selected' : '' }}>270°</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-check mt-1">
                                <input class="form-check-input" type="checkbox" name="elements[{{ $key }}][bold]" id="bold_{{ $key }}" {{ ($config['elements'][$key]['bold'] ?? false) ? 'checked' : '' }}>
                                <label class="form-check-label small" for="bold_{{ $key }}">Bold</label>
                            </div>
                        </div>
                        @endforeach
                    </div>
                </div>

                <!-- Buttons -->
                <div class="d-flex gap-2">
                    <button type="submit" class="btn btn-primary flex-grow-1">
                        <i class="fas fa-save"></i> Ruaj
                    </button>
                    <button type="button" class="btn btn-warning" onclick="previewPrint()">
                        <i class="fas fa-print"></i> Preview Print
                    </button>
                    <button type="button" class="btn btn-secondary" onclick="resetToDefault()">
                        <i class="fas fa-redo"></i> Reset
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<style>
    .form-control-sm {
        font-size: 0.85rem;
    }
    
    #preview {
        box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }
</style>

<script>
const SCALE = 3;
let config = @json($config);

// Initialize preview on load
document.addEventListener('DOMContentLoaded', function() {
    updatePreview();
    
    // Update preview on any input change
    document.getElementById('configForm').addEventListener('change', updatePreview);
    document.getElementById('configForm').addEventListener('input', updatePreview);
    
    // Handle logo visibility
    document.getElementById('show_logo').addEventListener('change', function() {
        document.getElementById('logoControls').style.display = this.checked ? 'block' : 'none';
    });
    
    // Handle form submission
    document.getElementById('configForm').addEventListener('submit', function(e) {
        e.preventDefault();
        saveConfig();
    });
});

function updatePreview() {
    const formData = new FormData(document.getElementById('configForm'));
    
    let width = parseFloat(formData.get('ticket_width_mm'));
    let height = parseFloat(formData.get('ticket_height_mm'));
    const orientation = formData.get('orientation');
    
    // Swap for portrait
    if (orientation === 'portrait') {
        [width, height] = [height, width];
    }
    
    const previewDiv = document.getElementById('preview');
    previewDiv.style.width = (width * SCALE) + 'px';
    previewDiv.style.height = (height * SCALE) + 'px';
    
    // Generate preview HTML
    let html = '';
    
    // Logo
    if (formData.get('show_logo')) {
        const logoHeight = parseFloat(formData.get('logo_height_mm'));
        const logoRotation = parseInt(formData.get('logo_rotation'));
        const logoTransform = logoRotation !== 0 ? `transform: rotate(${logoRotation}deg);` : '';
        html += `<div style="position: absolute; top: 10px; right: 10px;">
                    <img src="{{ asset('img/logo.png') }}" style="height: ${logoHeight * SCALE}px; ${logoTransform}" onerror="this.style.display='none'">
                 </div>`;
    }
    
    // Text fields
    let y = 20;
    const fields = ['project', 'part_name', 'dimensions', 'material', 'edge_banding', 'date'];
    fields.forEach(field => {
        if (formData.get(`fields_visible[${field}]`)) {
            const fontSize = parseInt(formData.get(`elements[${field}][font_size]`)) || 9;
            const rotation = parseInt(formData.get(`elements[${field}][rotation]`)) || 0;
            const bold = formData.get(`elements[${field}][bold]`) ? 'bold' : 'normal';
            const transform = rotation !== 0 ? `transform: rotate(${rotation}deg);` : '';
            
            html += `<div style="position: absolute; top: ${y}px; left: 10px; font-size: ${fontSize}px; font-weight: ${bold}; ${transform}">
                        [${field}]
                     </div>`;
            y += fontSize + 5;
        }
    });
    
    previewDiv.innerHTML = html;
}

function saveConfig() {
    const formData = new FormData(document.getElementById('configForm'));
    const data = {
        company_name: formData.get('company_name'),
        ticket_width_mm: parseFloat(formData.get('ticket_width_mm')),
        ticket_height_mm: parseFloat(formData.get('ticket_height_mm')),
        orientation: formData.get('orientation'),
        show_logo: formData.get('show_logo') === 'on',
        logo_height_mm: parseFloat(formData.get('logo_height_mm')),
        logo_rotation: parseInt(formData.get('logo_rotation')),
        print_offset_x: parseFloat(formData.get('print_offset_x')),
        print_offset_y: parseFloat(formData.get('print_offset_y')),
        elements: {},
        fields_visible: {}
    };
    
    // Collect text field settings
    const fields = ['project', 'part_name', 'dimensions', 'material', 'edge_banding', 'date'];
    fields.forEach(field => {
        data.elements[field] = {
            font_size: parseInt(formData.get(`elements[${field}][font_size]`)) || 9,
            rotation: parseInt(formData.get(`elements[${field}][rotation]`)) || 0,
            bold: formData.get(`elements[${field}][bold]`) === 'on'
        };
        data.fields_visible[field] = formData.get(`fields_visible[${field}]`) === 'on';
    });
    
    console.log('Saving:', data);
    
    fetch('{{ route('ticket-layout.update') }}', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
        },
        body: JSON.stringify(data)
    })
    .then(r => r.json())
    .then(data => {
        if (data.success) {
            Swal.fire('Sukses!', data.message, 'success');
        } else {
            Swal.fire('Gabim!', data.error || 'Ndodhi një gabim', 'error');
        }
    })
    .catch(err => {
        console.error('Error:', err);
        Swal.fire('Gabim!', 'Ndodhi një gabim në komunikim', 'error');
    });
}

function previewPrint() {
    window.open('{{ route('ticket-layout.preview') }}', '_blank');
}

function resetToDefault() {
    if (confirm('A jeni të sigurt?')) {
        fetch('{{ route('ticket-layout.reset') }}', {
            method: 'POST',
            headers: {
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content
            }
        })
        .then(r => r.json())
        .then(data => {
            if (data.success) {
                location.reload();
            }
        });
    }
}
</script>
@endsection
